# Generated by Django 3.1.7 on 2021-08-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BcvIndex',
            fields=[
                ('bcv', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('book', models.CharField(max_length=3)),
                ('bookLong', models.CharField(max_length=24)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Morphology',
            fields=[
                ('morphology', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('function', models.CharField(blank=True, max_length=24, null=True)),
                ('tense', models.CharField(blank=True, max_length=24, null=True)),
                ('voice', models.CharField(blank=True, max_length=24, null=True)),
                ('mood', models.CharField(blank=True, max_length=24, null=True)),
                ('person', models.CharField(blank=True, max_length=24, null=True)),
                ('case', models.CharField(blank=True, max_length=24, null=True)),
                ('gender', models.CharField(blank=True, max_length=24, null=True)),
                ('number', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strongs',
            fields=[
                ('strongs', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('lexicon', models.CharField(blank=True, max_length=36, null=True)),
                ('gloss', models.CharField(blank=True, max_length=64, null=True)),
                ('transliteration', models.CharField(blank=True, max_length=36, null=True)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greek', models.CharField(blank=True, max_length=36, null=True)),
                ('english', models.CharField(blank=True, max_length=36, null=True)),
                ('bcv', models.CharField(blank=True, max_length=6, null=True)),
                ('nestleAland', models.BooleanField()),
                ('bcvIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='gnt.bcvindex')),
                ('morphology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word', to='gnt.morphology')),
                ('strongs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word', to='gnt.strongs')),
            ],
        ),
    ]
