# Generated by Django 3.1.7 on 2022-01-16 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=16)),
                ('book_name_abbrev', models.CharField(max_length=3)),
                ('book_num_chapters', models.IntegerField()),
                ('book_num_verses', models.IntegerField()),
                ('book_num_words', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chap',
            fields=[
                ('chap_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('chap_num_verses', models.IntegerField()),
                ('chap_num_words', models.IntegerField()),
                ('chap_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chap', to='api.book')),
            ],
        ),
        migrations.CreateModel(
            name='Lexn',
            fields=[
                ('lexn_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('lexn_greek', models.CharField(blank=True, max_length=36, null=True)),
                ('lexn_english', models.CharField(blank=True, max_length=36, null=True)),
                ('lexn_transliteration', models.CharField(blank=True, max_length=36, null=True)),
                ('lexn_freq_nt', models.IntegerField(default=0)),
                ('lexn_function', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pars',
            fields=[
                ('pars_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pars_function', models.CharField(blank=True, max_length=5, null=True)),
                ('pars_tense', models.CharField(blank=True, max_length=2, null=True)),
                ('pars_voice', models.CharField(blank=True, max_length=1, null=True)),
                ('pars_mood', models.CharField(blank=True, max_length=1, null=True)),
                ('pars_person', models.CharField(blank=True, max_length=1, null=True)),
                ('pars_case', models.CharField(blank=True, max_length=1, null=True)),
                ('pars_gender', models.CharField(blank=True, max_length=1, null=True)),
                ('pars_number', models.CharField(blank=True, max_length=1, null=True)),
                ('pars_freq_nt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vers',
            fields=[
                ('vers_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('vers_ref', models.CharField(max_length=22)),
                ('vers_ref_abbrev', models.CharField(max_length=10)),
                ('vers_chap_url', models.CharField(max_length=6)),
                ('vers_chap_num', models.IntegerField()),
                ('vers_num', models.IntegerField()),
                ('vers_num_words', models.IntegerField()),
                ('vers_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vers', to='api.book')),
                ('vers_chap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vers', to='api.chap')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('word_greek', models.CharField(blank=True, max_length=36, null=True)),
                ('word_english', models.CharField(blank=True, max_length=36, null=True)),
                ('word_greek_punc', models.CharField(blank=True, max_length=2, null=True)),
                ('word_english_punc', models.CharField(blank=True, max_length=2, null=True)),
                ('word_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word', to='api.book')),
                ('word_chap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word', to='api.chap')),
                ('word_lexn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word', to='api.lexn')),
                ('word_pars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word', to='api.pars')),
                ('word_vers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word', to='api.vers')),
            ],
        ),
        migrations.CreateModel(
            name='Pdgm',
            fields=[
                ('pdgm_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pdgm_greek', models.CharField(blank=True, max_length=36, null=True)),
                ('pdgm_freq_nt', models.IntegerField(default=0)),
                ('pdgm_lexn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdgm', to='api.lexn')),
                ('pdgm_pars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdgm', to='api.pars')),
            ],
        ),
    ]
